[package]
name = "minhook_raw"
version = "0.1.5"
edition = "2021"
license = "Unlicense"
description = "Minhook binding for rust"
repository = "https://github.com/vSylva/minhook_raw"

[build-dependencies]
cc = "1.0.79"
